#
# Set a comma delimited list of util packages that modules should avoid using and
# use service reference instead.
#
java.osgi.reference.check=\
    com.liferay.exportimport.kernel.lar.ExportImportHelperUtil,\
    com.liferay.exportimport.kernel.lar.ExportImportProcessCallbackRegistryUtil,\
    com.liferay.exportimport.kernel.lar.PortletDataContextFactoryUtil,\
    com.liferay.exportimport.kernel.lar.PortletDataHandlerStatusMessageSenderUtil,\
    com.liferay.exportimport.kernel.staging.StagingUtil,\
    com.liferay.portal.kernel.backgroundtask.BackgroundTaskManagerUtil,\
    com.liferay.portal.kernel.backgroundtask.display.BackgroundTaskDisplayFactoryUtil,\
    com.liferay.portal.kernel.comment.CommentManagerUtil,\
    com.liferay.portal.kernel.util.HttpUtil,\
    com.liferay.portal.kernel.util.PortalUtil